### ISSUE TITLE
argument 'replicate' in function 'rename_dpcr' not recognised as factor

### ISSUE THREAD

**Issue by SebVen** [michbur/dpcR#29]
When one executes the following:
`>rename_dpcr(dpcr1, replicate = 2)`
or
`>rename_dpcr(dpcr1, replicate = "2")`

The following is returned:
`Error in checkSlotAssignment(object, name, value) : 
  assignment of an object of class “numeric” is not valid for slot ‘replicate’ in an object of class “ddpcr”; is(value, "factor") is not TRUE`

To overcome this, it is required to use
`>rename_dpcr(dpcr1, replicate = as.factor(2))`

Not a huge issue, but it would lead to cleaner code to have any numericals or strings already recognised as a factor

**Comment by michbur** [comment]
The function was improved according to your suggestion.
