### ISSUE TITLE
Major error in test_ratio

### ISSUE THREAD

**Issue by SebVen** [michbur/dpcR#30]
The `test_count` function as a wrapper for `rateratio.test` contains a major error.
The partition counts and individual lambda values (`Lambda1` and `Lambda2`) are each calculated correctly for a given number of molecules (m) and panel size (n). However, the incorrect `Lambda1/Lambda2` ratio is given as it is calculated by wrongly interpreting positive droplets as target molecules. This has a profound effect on the calculated ratio and confident intervals, especially at high target molecule concentrations.

**Comment by michbur** [comment]
Thanks you for letting us now! Unfortunately, I cannot localize the problem. I'm trying:

```R
test_counts(six_panels, model = "prop")
test_counts(six_panels, model = "ratio")
```

and both commands give results regarding the ratio consistent  with hand-performed computations. Can you give me an example?

**Comment by SebVen** [comment]
My apologies, the issue does not affect `test_count`, but rather `test.ratio`. On your project page indicates that this function has been depreciated, but it is still part of the R package.

**Comment by michbur** [comment]
Thanks for the clarification. The `test_ratio` function is indeed now redundant, because `test_counts` have its functionality and even more, for example:

```R
test_counts(extract_dpcr(six_panels, 1L:2))
```

I removed `test_ratio` from the package.
